version: '3.7'

services:

  db:
    image: mysql:5.6
    restart: on-failure
    environment:
      MYSQL_DATABASE: wp_evf
      MYSQL_USER: root
      MYSQL_PASSWORD: pass
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

  wordpress-everest-forms:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8084:80
    restart: on-failure
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wp_evf
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: pass
      WORDPRESS_TABLE_PREFIX: "wp_"
      WORDPRESS_DEBUG: 1
    volumes:
      - "./:/var/www/html/wp-content/plugins/everest-forms"
      - wordpress:/var/www/html

  wordpress-cli:
    depends_on:
      - db
      - wordpress-everest-forms
    image: wordpress:cli
    restart: on-failure
    user: xfs
    command: >
      /bin/sh -c '
      wp core install --url=http://localhost:8084 --title="Everest Forms" --admin_user=wpeverest --admin_password=pass --admin_email=admin@wpeverest.com --path=/var/www/html --skip-email;
      wp plugin activate everest-forms;
      wp theme install twentytwenty --activate;
      '
    volumes:
      - "./:/var/www/html/wp-content/plugins/everest-forms"
      - wordpress:/var/www/html

volumes:
  db:
  wordpress:
