#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

protected_branch="develop"

if read local_ref local_oid remote_ref remote_oid; then
    if [ "refs/heads/${protected_branch}" = "$remote_ref" ]; then
		>&2 echo "Warning: pushing directly to ${protected_branch}. Branch protection will reject this unless you're on an approved PR."
	fi
fi

exit 0
