#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

protected_branch="develop"

if read local_ref local_oid remote_ref remote_oid; then
    if [ "refs/heads/${protected_branch}" = "$remote_ref" ]; then
		if [ "$TERM" = "dumb" ]; then
			>&2 echo "Sorry, you are unable to push to ${protected_branch} using a GUI client! Please use git CLI."
			exit 1
		fi

		printf "%sYou're about to push to ${protected_branch}, is that what you intended? [y/N]: %s" "$(tput setaf 3)" "$(tput sgr0)"
		read -r proceed < /dev/tty
		echo

		if [ "$(echo "${proceed:-n}" | tr "[:upper:]" "[:lower:]")" = "y" ]; then
			echo "$(tput setaf 2)Brace yourself! Pushing to the ${protected_branch} branch...$(tput sgr0)"
			echo
			exit 0
		fi

		echo "$(tput setaf 1)Push to ${protected_branch} cancelled!$(tput sgr0)"
		echo
		exit 1
	fi
fi
