name: Build Testable ZIP

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [develop]
  workflow_dispatch:

jobs:
  zip:
    uses: wpeverest/.github/.github/workflows/pr-build-zip.yml@master
    with:
      node-version: '20.x'
      php-version: '7.4'
      package-manager: npm
      composer-install: true
      build-command: npm run build && mkdir -p everest-forms && rsync -rc --exclude-from=.distignore ./ ./everest-forms --delete --delete-excluded && zip -r everest-forms.zip everest-forms
      zip-glob: 'everest-forms.zip'
      artifacts-bucket: themegrill-pr-artifacts
      public-base-url: https://themegrill-pr-artifacts.s3.amazonaws.com
      s3-region: us-east-1
    secrets:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      ARTIFACTS_KEY: ${{ secrets.ARTIFACTS_KEY }}
      ARTIFACTS_SECRET: ${{ secrets.ARTIFACTS_SECRET }}
