name: Run code sniff on PR
# on:
#   push:
#     branches:
#       - "develop"
#       - "implement/php-unit-test"
jobs:
  test:
    name: PHP Coding Standards
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Composer cache
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: phpcs-composer-${{ hashFiles('composer.json') }}

      - name: PHPCS cache
        uses: actions/cache@v1
        with:
          path: tests/cache
          # This uses the hash of everest-forms.php in its cache key because Actions doesn't support
          # always pulling in a cache file and simultaneously always updating it, unlike Travis.
          # This way we always pull in a cache file and refresh it with each new version of EVF.
          key: phpcs-${{ hashFiles('everest-forms.php') }}

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "7.3"
          coverage: none
        env:
          fail-fast: true

      - name: Debugging
        run: |
          php --version
          composer --version

      - name: Composer validate
        run: composer validate --strict

      - name: Install dependencies
        run: |
          composer install --prefer-dist

      - name: Run code sniffer
        run: |
          composer require staabm/annotate-pull-request-from-checkstyle="^1.6"
          composer test:cs2pr
