name: Test
on:
  push:
    branches:
      - "develop"
      - "implement/php-unit-test"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    strategy:
      matrix:
        php: ["7.3", "5.6"]
        wp: ["*", "dev-nightly"]
      fail-fast: false
    name: WP ${{ matrix.wp }} / PHP ${{ matrix.php }}
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Composer cache
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache
          key: ${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: mysqli, xmlwriter
          coverage: none
        env:
          fail-fast: true

      - name: Debugging
        run: |
          php --version
          php -m
          composer --version
          mysql --version
      - name: Install dependencies
        run: |
          sudo systemctl start mysql.service
          composer install --prefer-dist
          composer require --dev --update-with-dependencies --prefer-dist roots/wordpress="${{ matrix.wp }} || *" wp-phpunit/wp-phpunit="${{ matrix.wp }} || *"
      - name: Run unit tests
        run: composer test
        env:
          MYSQL_DATABASE: wordpress
          WP_TESTS_DB_PASS: root
